In [1]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
triangle = [[4.0, 4.0],[2.0, 1.0], [6.0, 1.0]]
points = torch.tensor(triangle)
points

tensor([[4., 4.],
        [2., 1.],
        [6., 1.]])

In [4]:
points.shape

torch.Size([3, 2])

In [5]:
points[0,1]

tensor(4.)

In [6]:
points[0:1]

tensor([[4., 4.]])